project:
  type: book

book:
  title: "Verallgemeinerung der $\\kdotp$-Theorie für periodische Störungen"
  output-file: "stubner_1999_verallgemeinerung_kp_theorie"
  author: "Ralf Stubner"
  date: "März 1999"
  chapters:
    - index.qmd
    - period_efa.qmd
    - anwendung.qmd
    - ergebnisse.qmd
    - zusammenfassung.qmd
  appendices:
    - lcao.qmd
    - ergeb-BGR.qmd
    - references.qmd
    - danke.qmd
    - erklaerung.qmd
  search: true
  repo-url: https://github.com/rstub/diploma-thesis/
  downloads: [pdf]
  sharing: [twitter, facebook]

#pdf-engine: xelatex
fontfamily: mathpazo
fontfamilyoptions: [osf,slantedGreek]
linestretch: 1.15
indent: true
lang: de
crossref:
  fig-title: Abbildung     # (default is "Figure")
  tbl-title: Tabelle     # (default is "Table")
  fig-prefix: Abb.   # (default is "fig.")
  tbl-prefix: Tab.    # (default is "tbl.")
  sec-prefix: Kap.
  eq-prefix: Gl.

link-citations: true
bibliography: references.bib
csl: reviews-of-modern-physics-with-titles.csl

format:
  html:
    theme: cosmo
    html-math-method: katex
    keep-md: true
  pdf:
    documentclass: scrbook
    classoption: [10pt,a5paper,1headlines,headinclude,smallheadings,cleardoubleplain,bibtotoc]
    keep-md: true
    keep-tex: true
    include-in-header: header.tex
    #cite-method: biblatex
    #biblatexoptions: [style=phys]
