```{r, results='asis', echo=FALSE, eval=knitr::is_html_output()}
input <- file("header.tex")
cat(sub("%.*$", "", readLines(input)), sep = "\n")
close(input)
```

# Ergebnisse und Diskussion {#sec-ergebnisse}

## Diagonalisieren des Hamilton-Operators {#sec-diag}

Die Diagonalisierung des $\kdotp$-Hamilton-Operators \eqref{eq:k.p-H} wollen wir in mehreren Schritten vornehmen. Die Idee dabei ist, daß wir zunächst Gl.\~\eqref{eq:k.p-H} für $k=0$ diagonalisieren. Dadurch erhalten wir neue Basisfunktionen, die sich als Linearkombination der alten Basisfunktionen darstellen lassen, so daß wir die $\kdotp$-Wechselwirkungen zwischen diesen neuen Basisfunktionen angeben können. Danach können wir dann diese Kopplungen in zweiter Ordnung Störungstheorie behandeln, um die effektiven Massen zu erhalten.

## Entkopplung von Valenz- und Leitungsband {#sec-V15}

In Gl.\~\eqref{eq:V15-V11} haben wir gesehen, daß $\V{15}$, verglichen mit den dazugehörigen Energienennern, das Matrixelement mit dem geringsten Effekt ist. Wie wir noch sehen werden, gilt $|\V{11}| \approx 200\;\text{meV}$ für die höchstgeordneten Proben, die im Experiment bisher gefunden wurden. Setzen wir aber nun die Werte aus Tab.\~\ref{tab:Em*P} ein, so erhalten wir, daß auch $|\V{15}| \approx 200\;\text{meV}$ ist und damit eine Größenordnung kleiner als der dazugehörige Energienenner. Dies rechtfertigt es, diese Kopplung störungstheoretisch zu behandeln.

Dabei wollen wir Löwdin-Störungstheorie [@lowd:51] verwenden, wie wir sie in @sec-standard-k.p beschrieben haben. Da wir hier eine Entkopplung von Valenz- und Leitungsband durchführen möchten, bedeutet dies, daß wir einmal die Leitungsbänder als Gruppe $\raum{A}$ betrachten und die Valenzbänder als Gruppe $\raum{B}$ und dann diese Rollen vertauschen.

Führen wir dies für den Hamilton-Operator \eqref{eq:k.p-H} durch, so müssen wir nur folgende Energien abändern, um die Kopplung zwischen Valenz- und Leitungsband in zweiter Ordnung zu beseitigen:
