```{r, results='asis', echo=FALSE, eval=knitr::is_html_output()}
input <- file("header.tex")
cat(sub("%.*$", "", readLines(input)), sep = "\n")
close(input)
```

# Die Methode der Linearkombination atomarer Orbitale {#sec-lcao}

## Grundlagen der LCAO-Methode {#sec-lcao-allgemein}

In der Methode der Linearkombination atomarer Orbitale \[*linear
combination of atomic orbitals* (LCAO), oft auch *tight-binding
approximation* (TBA) genannt\] verwenden wir Bloch-Summen $$
  \Phi_{i \vec{k}} (\vec{r}) = \frac{1}{\sqrt{N}} \sum_{j} e^{i
  \sprod{k}{R_{\mathnormal{j}}}} \phi_{i} (\vec{r} - \vec{R_{\mathnormal{j}}})
$$ als Basis für die Entwicklung der Lösung des Problems eines Elektrons
in einem periodischen Potential. Die
$\phi_{i} (\vec{r} - \vec{R_{\mathnormal{i}}})$ stellen dabei atomare
Orbitale dar, die auf dem Atom am Ort $\vec{R_{\mathnormal{j}}}$
lokalisiert sind und durch den Index $i$ charakterisiert werden. Die
Summe läuft über alle $N$ äquivalenten Atome des Kristalls. Die diskrete
Translationssymmetrie wird durch den Wellenvektor $\vec{k}$
charakterisiert. Für jedes Atom in der Einheitszelle und alle atomaren
Wellenfunktionen können wir solch eine Blochsumme konstruieren, und
erhalten so eine Basis für die Entwicklung der Wellenfunktionen. Eine
Lösung für des Problems eines Elektrons in einem periodischen Potential
läßt sich dann als
$\psi_{n\vec{k}}(\vec{r}) = \sum_{i} a_{ni} \Phi_{i \vec{k}}$ schreiben,
wobei die Summe über alle Atome in der Einheitszelle und alle atomaren
Wellenfunktionen in der Basis geht.

Schreiben wir den Hamilton-Operator für das periodische Potential in
dieser Basis, so erhalten wir viele Matrixelemente, die nur schwer zu
berechnen sind. Deshalb wird die LCAO-Methode seit @slko:54 meist als
Interpolationsmethode verwendet. Dabei wird die Anzahl der
Matrixelemente durch verschieden Näherungen reduziert. Danach wird der
Wert dieser Matrixelemente an experimentelle oder aus anderen Rechnungen
bekannte Energieeigenwerte an Punkten hoher Symmetrie in der
Brillouin-Zone angepaßt. Ist dies geschehen, so können wir die
Dispersion für die gesamte Brillouin-Zone berechnen. Typische Näherungen
sind, daß wir nur wenige Orbitale pro Atom in die Basis aufnehemen (hier
$sp^{3}$ bzw. $sp^{3}d^{5}s^{\ast}$), Wechselwirkungen ab einer gewissen
Entfernung zwischen den Atomen vernachlässigen (hier nur
Nächste-Nachbar-Wechselwirkungen) und die auftretenden Matrixelemente
durch eine Kombination sogenannter Zwei-Zentren-Integrale (*two-center
integrals*) nähern.[^1] Diese Reduzierung der Anzahl der Parameter ist
auch deshalb notwendig, um bei den meist wenigen bekannten
Energieeigenwerten ein aussagekräftiges Modell zu
erhalten.

[^1]: Diese sind zu den kovalenten Bindungen in der Chemie vergleichbar.

## $sp^{3}$-Basis für qualitative Aussagen {#sec-sp3}

Wie @harr:80 gezeigt hat, lassen sich viele Eigenschaften tetraedrisch
koordinierter Halbleiter schon in einer $sp^{3}$-Basis mit nur
Nächste-Nachbar-Wechselwirkungen qualitativ erklären. Wir wollen ein
solches Modell hier benutzen, um die in @sec-phase gezeigte Form der
Wellenfuntkionen zu erklären.
